name: CI/CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '7.x'

    - name: Restore dependencies
      run: dotnet restore UXI_Mortgage/UXI_Mortgage/UXI_Mortgage/UXI_Mortgage.csproj

    - name: Build
      run: dotnet build UXI_Mortgage/UXI_Mortgage/UXI_Mortgage/UXI_Mortgage.csproj --configuration Release --no-restore

    - name: Run tests
      run: dotnet test UXI_Mortgage/UXI_Mortgage/UXI_Mortgage/UXI_Mortgage.csproj --no-restore --verbosity normal

    - name: Publish
      run: dotnet publish UXI_Mortgage/UXI_Mortgage/UXI_Mortgage/UXI_Mortgage.csproj --configuration Release --output ./output

    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: build-artifacts
        path: ./output

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'your-app-name'
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: './output'
