name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: [ windows-latest ]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup MSbuild
      uses: microsoft/setup-msbuild@v2

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v2.0.0

    - name: Restore NuGet packages
      run: nuget restore BugGadiant.UXI_Mortgage.sln

    - name: Build solution
      run: msbuild BugGadiant.UXI_Mortgage.sln /p:Configuration=Release

  test:
    runs-on: [ windows-latest ]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup MSbuild
      uses: microsoft/setup-msbuild@v2

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v2.0.0

    - name: Restore NuGet packages
      run: nuget restore BugGadiant.UXI_Mortgage.sln

    - name: Run tests
      run: msbuild BugGadiant.UXI_Mortgage.sln /p:Configuration=Release /t:Test

  deploy:
    runs-on: [ windows-latest ]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Deploy to server
      run: |
        echo "Deploying to server..."
        # Add your deployment script/commands here
